image: python:latest

stages:
  - lint
  - test
  - deploy

variables: 
  PROJECT_SHORT_NAME: URLShortner

black_job:
  stage: lint
  before_script:
    - pip install black
  script:
    - black --fast .

flake8_job:
  stage: lint
  before_script:
    - pip install flake8
  script:
    - flake8 .

pytest_job:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest . -v -s
  only:
    changes:
      - src/**/*
      - tests/*
      - '*.py'
  coverage: '/TOTAL.*\s+(\d+%)$/'

deploy_stagging_job:
  stage: deploy
  variables:
    TAG: stagging
  before_script:
    - export PROJECT_VERSION=1.0.$(git rev-list --count HEAD)-$TAG
  script:
    - printenv PROJECT_VERSION
  only:
    - stagging

deploy_production_job:
  stage: deploy
  variables:
    TAG: prod
  before_script:
    - export PROJECT_VERSION=1.0.$(git rev-list --count HEAD)-$TAG
  script:
    - printenv PROJECT_VERSION
  only:
    - master