image: python:latest

stages:
  - lint
  - test
  - stagging
  - deploy

variables: 
  PROJECT_SHORT_NAME: bolinha

before_script:
    - pip install -r requirements.txt
    - echo "ola mundo"

# test_job:
#   stage: test
#   before_script:
#     # Count the number of commits on branch
#     - export VERSION=1.0.$(git rev-list --count HEAD)-$TAG
#   script:
#     - pytest .
#   coverage: '/TOTAL.*\s+(\d+%)$/'