image: python:latest

stages:
  - lint
  - test
  - deploy

variables: 
  PROJECT_SHORT_NAME: URLShortner
  PROJECT_VERSION: 1.0.$(git rev-list --count HEAD)-$TAG

black_job:
  stage: lint
  before_script:
    - pip install black
  script:
    - black --fast .

flake8_job:
  stage: lint
  before_script:
    - pip install flake8
  script:
    - flake8 .

pytest_job:
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest . -v -s
  coverage: '/TOTAL.*\s+(\d+%)$/'