default:
  image: python:latest
  before_script:
    - export VERSION=1.0.$(git rev-list --count HEAD)-$TAG
    - pip install -r requirements.txt

variables: 
  PROJECT_SHORT_NAME: URLShortner

lint_job:
  stage: test
  script:
    - black --fast .
    - flake8 .

test_job:
  stage: test
  script:
    - pytest . -v -s
  coverage: '/TOTAL.*\s+(\d+%)$/'