repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
# -   repo: local
#     hooks:
#     - id: pytest
#       name: pytest
#       language: system
#       entry: pytest -v
#       always_run: true
#       pass_filenames: false
#       stages: [commit]
-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: bash -c 'pip freeze > requirements.txt --exclude pywin32; git add requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]