image: python:latest

stages:
  - test
  - deploy

variables: 
  PROJECT_SHORT_NAME: bolinha

before_script:
    - pip install -r requirements.txt

test_job:
  stage: test
  before_script:
    # Count the number of commits on branch
    - export VERSION=1.0.$(git rev-list --count HEAD)-$TAG
  script:
    - pytest .
  coverage: '/TOTAL.*\s+(\d+%)$/'